

```{r}
library(tidyverse)
library(sf)

```


## Unemployment 

```{r}

# read the data 

unm <- st_read('F-dataset/unemployment/Unemployment.shp')

library(mapsf)
#> Le chargement a nécessité le package : sf
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0; sf_use_s2() is TRUE
# Import the sample dataset
# Plot the base map
# Plot non European space
plot(world.spdf, col  = "#E3DEBF", border = NA, add = TRUE)

mf_export(x = unm, filename = "fixed_width.png", width = 700, res = 100)

mf_theme(x = "dark")
mf_map(x = unm)
mf_shadow(unm, col = "grey10", add = TRUE)
# Plot proportional symbols
mf_map(x = unm, var = "X2019", type = "choro", pal = "Dark Mint", 
       breaks = "quantile", 
       nbreaks = 6, 
       leg_title = "Unemployment rate\n(%)",
       add = TRUE)
# Plot a map layout
mf_layout(title = "Unemployment rate (%) in 2019", 
          credits = "ESPON 2022")


```


```{r}

library(mapsf)
library(potential)

mf_map(unm, col= "grey80", border = "white", lwd = .4)
y <- create_grid(x = unm, res = 100000)
mf_map(y, pch = 23, add = TRUE, bg = "blue", cex = .5 )

d <- create_matrix(x = n3_pt, y = y)

y$pot <- potential(x = n3_pt, y = y, d = d,
                   var = "POP19", fun = "e",
                   span = 75000, beta = 2)
mf_map(n3_poly, col= "grey80", border = "white", lwd = .4)
mf_map(y, var = "pot", type = "prop", 
       inches= .1, 
       lwd = .5, 
       leg_val_cex = .5, 
       leg_val_rnd = -3,
       leg_frame = TRUE, 
       leg_pos = "topright")

```

